### ISSUE TITLE
class_error =100.0

### ISSUE THREAD

**Issue by August66** [MoChen-bop/DETR-Paddle#1]
hi,i have a question, when i trian the VG set ,i see it sometimes class_error=100.0 and class_error not 100.0,
Can you help me see  is it normal?How should I modify it？thanks.

![image](https://user-images.githubusercontent.com/49583225/108991900-9f6f9880-76d3-11eb-876b-ae8d2b516387.png)

**Comment by August66** [comment]
and how long time you have trian?

**Comment by huochf** [comment]
1. At beginning, the model's performance  is no better than random guess, so class_error = 1 - accuracy -> 89 / 90 ( for 90 classes).
2. This set of code consumes memory heavily than official released code due to frequently convertion between paddle.Variable and numpy.ndarray .  Need to make some optimization in matching loss.
3. I hope you use the official released code (pytorch) to train. Or other more efficient DETR, such as deformable DETR or TSP-RCNN.  DETR need to train more than 3 days in 8 V100 for COCO dataset.

**Comment by August66** [comment]
OK，thanks,i find thecode run in the cpu ,but not in the GPU ,so the times looks so long,thanks you ,i`ll try another code(pytorch).
